# Generated by Django 4.2.7 on 2025-09-20 02:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Offer title (e.g., 'Christmas Special')", max_length=200)),
                ('description', models.TextField(help_text='Detailed offer description')),
                ('offer_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount Discount'), ('free_delivery', 'Free Delivery'), ('buy_one_get_one', 'Buy One Get One'), ('special', 'Special Offer')], default='percentage', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('paused', 'Paused')], default='draft', max_length=10)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed discount amount', max_digits=10, null=True)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount to apply offer', max_digits=10)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('banner_image', models.ImageField(blank=True, help_text='Banner image for the offer', null=True, upload_to='offers/banners/')),
                ('background_color', models.CharField(default='#FF6B6B', help_text='Background color (hex code)', max_length=7)),
                ('text_color', models.CharField(default='#FFFFFF', help_text='Text color (hex code)', max_length=7)),
                ('is_homepage_featured', models.BooleanField(default=True, help_text='Show on homepage')),
                ('is_popup', models.BooleanField(default=False, help_text='Show as popup on homepage')),
                ('target_user_types', models.JSONField(default=list, help_text='Target specific user types (admin, customer, etc.)')),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('max_usage', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this offer can be used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['-created_at'],
            },
        ),
    ]
