# Generated by Django 4.2.7 on 2025-09-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_ingredient_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
