# Generated by Django 4.2.7 on 2025-09-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_remove_ingredient_category_delete_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
