# Generated by Django 4.2.7 on 2025-10-03 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_ingredient_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="type",
        ),
    ]
