# Generated by Django 4.2.7 on 2025-09-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_current_latitude_order_current_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
