# Generated by Django 4.2.7 on 2025-09-20 15:35

from django.db import migrations


def clear_india_country(apps, schema_editor):
    """Clear 'India' from country field to make it empty"""
    ShippingAddress = apps.get_model('orders', 'ShippingAddress')
    ShippingAddress.objects.filter(country='India').update(country='')


def reverse_clear_india_country(apps, schema_editor):
    """Reverse migration - set empty countries back to 'India'"""
    ShippingAddress = apps.get_model('orders', 'ShippingAddress')
    ShippingAddress.objects.filter(country='').update(country='India')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_shippingaddress_country'),
    ]

    operations = [
        migrations.RunPython(clear_india_country, reverse_clear_india_country),
    ]
